In [1]:
from datasets import load_dataset

df = load_dataset("jhu-clsp/CLERC")["train"].to_pandas()
sample_df = df.sample(50000, random_state=42)
sample_df

Loading dataset shards:   0%|          | 0/31 [00:00<?, ?it/s]

,query_id,query,positive_passages,negative_passages
88726,679374,"work-related death, unless he either was menta...","[{'docid': '22038167', 'title': '', 'text': 'i...","[{'docid': '10355615', 'title': '', 'text': 'd..."
109716,644665,(Ct. Cl. of U. S.) 36 F.(2d) 529; decision fil...,"[{'docid': '2821258', 'title': '', 'text': 'th...","[{'docid': '21627454', 'title': '', 'text': 'C..."
140095,165386,verdict does not give extra weight or a presum...,"[{'docid': '22719999', 'title': '', 'text': 'o...","[{'docid': '13639698', 'title': '', 'text': '3..."
103843,404944,person would “believe that the agent is violat...,"[{'docid': '6266757', 'title': '', 'text': 'di...","[{'docid': '293090', 'title': '', 'text': 'is ..."
158242,43988,purposes and objectives. Narrow technicalities...,"[{'docid': '8793320', 'title': '', 'text': 'ch...","[{'docid': '16592179', 'title': '', 'text': 'j..."
...,...,...,...,...
27496,349042,"""rights. In addition, with respect to the Merc...","[{'docid': '14872194', 'title': '', 'text': 'o...","[{'docid': '47657', 'title': '', 'text': 'Debt..."
105594,19396,that rejection of two of his claims was proper...,"[{'docid': '22656256', 'title': '', 'text': 'h...","[{'docid': '22016411', 'title': '', 'text': 'n..."
237269,256459,"6, 20 L.Ed.2d 476 (1968). During trial appella...","[{'docid': '282086', 'title': '', 'text': 'for...","[{'docid': '1590142', 'title': '', 'text': 'No..."
14862,408356,were inadequate because the court failed to pr...,"[{'docid': '9597392', 'title': '', 'text': 'lo...","[{'docid': '3842689', 'title': '', 'text': 'We..."
25631,32141,""" REDACTED the Second Circuit discussed its h...","[{'docid': '22955785', 'title': '', 'text': 'n...","[{'docid': '6764197', 'title': '', 'text': 'th..."

In [2]:
sample_df.to_pickle("../resources/CLERC_sample.pkl")

In [1]:
import pandas as pd
df = pd.read_pickle("../resources/CLERC_sample.pkl")
df

,query_id,query,positive_passages,negative_passages
88726,679374,"work-related death, unless he either was menta...","[{'docid': '22038167', 'title': '', 'text': 'i...","[{'docid': '10355615', 'title': '', 'text': 'd..."
109716,644665,(Ct. Cl. of U. S.) 36 F.(2d) 529; decision fil...,"[{'docid': '2821258', 'title': '', 'text': 'th...","[{'docid': '21627454', 'title': '', 'text': 'C..."
140095,165386,verdict does not give extra weight or a presum...,"[{'docid': '22719999', 'title': '', 'text': 'o...","[{'docid': '13639698', 'title': '', 'text': '3..."
103843,404944,person would “believe that the agent is violat...,"[{'docid': '6266757', 'title': '', 'text': 'di...","[{'docid': '293090', 'title': '', 'text': 'is ..."
158242,43988,purposes and objectives. Narrow technicalities...,"[{'docid': '8793320', 'title': '', 'text': 'ch...","[{'docid': '16592179', 'title': '', 'text': 'j..."
...,...,...,...,...
27496,349042,"""rights. In addition, with respect to the Merc...","[{'docid': '14872194', 'title': '', 'text': 'o...","[{'docid': '47657', 'title': '', 'text': 'Debt..."
105594,19396,that rejection of two of his claims was proper...,"[{'docid': '22656256', 'title': '', 'text': 'h...","[{'docid': '22016411', 'title': '', 'text': 'n..."
237269,256459,"6, 20 L.Ed.2d 476 (1968). During trial appella...","[{'docid': '282086', 'title': '', 'text': 'for...","[{'docid': '1590142', 'title': '', 'text': 'No..."
14862,408356,were inadequate because the court failed to pr...,"[{'docid': '9597392', 'title': '', 'text': 'lo...","[{'docid': '3842689', 'title': '', 'text': 'We..."
25631,32141,""" REDACTED the Second Circuit discussed its h...","[{'docid': '22955785', 'title': '', 'text': 'n...","[{'docid': '6764197', 'title': '', 'text': 'th..."

In [1]:
# Requires transformers>=4.48.0
from sentence_transformers import CrossEncoder

model = CrossEncoder(
    "Alibaba-NLP/gte-reranker-modernbert-base",
    automodel_args={"torch_dtype": "auto"},
)

pairs = [
    ["what is the capital of China?", "Beijing"],
    ["how to implement quick sort in python?","Introduction of quick sort"],
    ["how to implement quick sort in python?", "The weather is nice today"],
]

scores = model.predict(pairs)
print(scores)
# [0.8945664  0.9213594  0.15742092]
# NOTE: Sentence Transformers calls Softmax over the outputs by default, hence the scores are in [0, 1] range.

The CrossEncoder `automodel_args` argument was renamed and is now deprecated, please use `model_kwargs` instead.

config.json: 0.00B [00:00, ?B/s]

D:\App\Anaconda\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Hang\.cache\huggingface\hub\models--Alibaba-NLP--gte-reranker-modernbert-base. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

model.safetensors:   0%|          | 0.00/598M [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/694 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

[0.89456636 0.9213594  0.15742084]

In [2]:
# Requires transformers>=4.48.0
from sentence_transformers import SentenceTransformer
from sentence_transformers.util import cos_sim

input_texts = [
    "what is the capital of China?",
    "how to implement quick sort in python?",
    "Beijing",
    "sorting algorithms"
]

model = SentenceTransformer("Alibaba-NLP/gte-modernbert-base")
embeddings = model.encode(input_texts)
print(embeddings.shape)
# (4, 768)

similarities = cos_sim(embeddings[0], embeddings[1:])
print(similarities)
# tensor([[0.4289, 0.7131, 0.3366]])

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

D:\App\Anaconda\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Hang\.cache\huggingface\hub\models--Alibaba-NLP--gte-modernbert-base. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

config_sentence_transformers.json:   0%|          | 0.00/205 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

config.json: 0.00B [00:00, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

model.safetensors:   0%|          | 0.00/298M [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/694 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/297 [00:00<?, ?B/s]

(4, 768)
tensor([[0.4289, 0.7131, 0.3366]])